// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Join struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LogicalTime     int32                  `protobuf:"varint,1,opt,name=LogicalTime,proto3" json:"LogicalTime,omitempty"`
	ParticipantName string                 `protobuf:"bytes,2,opt,name=participantName,proto3" json:"participantName,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Join) Reset() {
	*x = Join{}
	mi := &file_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Join) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Join) ProtoMessage() {}

func (x *Join) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Join.ProtoReflect.Descriptor instead.
func (*Join) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{0}
}

func (x *Join) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

func (x *Join) GetParticipantName() string {
	if x != nil {
		return x.ParticipantName
	}
	return ""
}

type Leave struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LogicalTime     int32                  `protobuf:"varint,1,opt,name=LogicalTime,proto3" json:"LogicalTime,omitempty"`
	ParticipantName string                 `protobuf:"bytes,2,opt,name=participantName,proto3" json:"participantName,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Leave) Reset() {
	*x = Leave{}
	mi := &file_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Leave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Leave) ProtoMessage() {}

func (x *Leave) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Leave.ProtoReflect.Descriptor instead.
func (*Leave) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{1}
}

func (x *Leave) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

func (x *Leave) GetParticipantName() string {
	if x != nil {
		return x.ParticipantName
	}
	return ""
}

type Chat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogicalTime   int32                  `protobuf:"varint,1,opt,name=LogicalTime,proto3" json:"LogicalTime,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	SenderName    string                 `protobuf:"bytes,3,opt,name=senderName,proto3" json:"senderName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{2}
}

func (x *Chat) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

func (x *Chat) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Chat) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

type ParticipantName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Join          string                 `protobuf:"bytes,2,opt,name=Join,proto3" json:"Join,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParticipantName) Reset() {
	*x = ParticipantName{}
	mi := &file_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantName) ProtoMessage() {}

func (x *ParticipantName) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantName.ProtoReflect.Descriptor instead.
func (*ParticipantName) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{3}
}

func (x *ParticipantName) GetJoin() string {
	if x != nil {
		return x.Join
	}
	return ""
}

var File_proto_proto protoreflect.FileDescriptor

const file_proto_proto_rawDesc = "" +
	"\n" +
	"\vproto.proto\"R\n" +
	"\x04Join\x12 \n" +
	"\vLogicalTime\x18\x01 \x01(\x05R\vLogicalTime\x12(\n" +
	"\x0fparticipantName\x18\x02 \x01(\tR\x0fparticipantName\"S\n" +
	"\x05Leave\x12 \n" +
	"\vLogicalTime\x18\x01 \x01(\x05R\vLogicalTime\x12(\n" +
	"\x0fparticipantName\x18\x02 \x01(\tR\x0fparticipantName\"\\\n" +
	"\x04Chat\x12 \n" +
	"\vLogicalTime\x18\x01 \x01(\x05R\vLogicalTime\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1e\n" +
	"\n" +
	"senderName\x18\x03 \x01(\tR\n" +
	"senderName\"%\n" +
	"\x0fparticipantName\x12\x12\n" +
	"\x04Join\x18\x02 \x01(\tR\x04Join2/\n" +
	"\bChitChat\x12#\n" +
	"\bJoinChat\x12\x10.participantName\x1a\x05.JoinB\x1aZ\x18SimpleService/grpc/protob\x06proto3"

var (
	file_proto_proto_rawDescOnce sync.Once
	file_proto_proto_rawDescData []byte
)

func file_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)))
	})
	return file_proto_proto_rawDescData
}

var file_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_proto_goTypes = []any{
	(*Join)(nil),            // 0: Join
	(*Leave)(nil),           // 1: Leave
	(*Chat)(nil),            // 2: Chat
	(*ParticipantName)(nil), // 3: participantName
}
var file_proto_proto_depIdxs = []int32{
	3, // 0: ChitChat.JoinChat:input_type -> participantName
	0, // 1: ChitChat.JoinChat:output_type -> Join
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_proto_init() }
func file_proto_proto_init() {
	if File_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_depIdxs,
		MessageInfos:      file_proto_proto_msgTypes,
	}.Build()
	File_proto_proto = out.File
	file_proto_proto_goTypes = nil
	file_proto_proto_depIdxs = nil
}
