// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Ls            int64                  `protobuf:"varint,3,opt,name=Ls,proto3" json:"Ls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatIn) Reset() {
	*x = ChatIn{}
	mi := &file_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatIn) ProtoMessage() {}

func (x *ChatIn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatIn.ProtoReflect.Descriptor instead.
func (*ChatIn) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{0}
}

func (x *ChatIn) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ChatIn) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatIn) GetLs() int64 {
	if x != nil {
		return x.Ls
	}
	return 0
}

type ChatOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Ts            int64                  `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Ls            int64                  `protobuf:"varint,4,opt,name=Ls,proto3" json:"Ls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatOut) Reset() {
	*x = ChatOut{}
	mi := &file_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatOut) ProtoMessage() {}

func (x *ChatOut) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatOut.ProtoReflect.Descriptor instead.
func (*ChatOut) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{1}
}

func (x *ChatOut) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ChatOut) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatOut) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *ChatOut) GetLs() int64 {
	if x != nil {
		return x.Ls
	}
	return 0
}

var File_proto_proto protoreflect.FileDescriptor

const file_proto_proto_rawDesc = "" +
	"\n" +
	"\vproto.proto\"D\n" +
	"\x06ChatIn\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x0e\n" +
	"\x02Ls\x18\x03 \x01(\x03R\x02Ls\"U\n" +
	"\aChatOut\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\x03R\x02ts\x12\x0e\n" +
	"\x02Ls\x18\x04 \x01(\x03R\x02Ls2)\n" +
	"\bChitChat\x12\x1d\n" +
	"\x04Chat\x12\a.ChatIn\x1a\b.ChatOut(\x010\x01B\x15Z\x13ChitChat/grpc/protob\x06proto3"

var (
	file_proto_proto_rawDescOnce sync.Once
	file_proto_proto_rawDescData []byte
)

func file_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)))
	})
	return file_proto_proto_rawDescData
}

var file_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_proto_goTypes = []any{
	(*ChatIn)(nil),  // 0: ChatIn
	(*ChatOut)(nil), // 1: ChatOut
}
var file_proto_proto_depIdxs = []int32{
	0, // 0: ChitChat.Chat:input_type -> ChatIn
	1, // 1: ChitChat.Chat:output_type -> ChatOut
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_proto_init() }
func file_proto_proto_init() {
	if File_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_depIdxs,
		MessageInfos:      file_proto_proto_msgTypes,
	}.Build()
	File_proto_proto = out.File
	file_proto_proto_goTypes = nil
	file_proto_proto_depIdxs = nil
}
